Repository terraform-providers/terraform-provider-venafi, pull requests merged in 2020-03, with the labels that each got.

#9 Provide origin tag
  go.mod
  go.sum
  venafi/provider.go
  venafi/resource_venafi_certificate.go
  vendor/github.com/Venafi/vcert/Makefile
  vendor/github.com/Venafi/vcert/README.md
  vendor/github.com/Venafi/vcert/client.go
  vendor/github.com/Venafi/vcert/go.mod
  vendor/github.com/Venafi/vcert/go.sum
  vendor/github.com/Venafi/vcert/listener.go
  vendor/github.com/Venafi/vcert/pkg/certificate/certificate.go
  vendor/github.com/Venafi/vcert/pkg/certificate/certificateCollection.go
  vendor/github.com/Venafi/vcert/pkg/endpoint/endpoint.go
  vendor/github.com/Venafi/vcert/pkg/venafi/cloud/cloud.go
  vendor/github.com/Venafi/vcert/pkg/venafi/cloud/connector.go
  vendor/github.com/Venafi/vcert/pkg/venafi/cloud/error.go
  vendor/github.com/Venafi/vcert/pkg/venafi/fake/ca.go
  vendor/github.com/Venafi/vcert/pkg/venafi/fake/connector.go
  vendor/github.com/Venafi/vcert/pkg/venafi/tpp/connector.go
  vendor/github.com/Venafi/vcert/pkg/venafi/tpp/search.go
  vendor/github.com/Venafi/vcert/pkg/venafi/tpp/tpp.go
  vendor/github.com/Venafi/vcert/pkg/verror/errors.go
  vendor/github.com/Venafi/vcert/vcert.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#10 Small reame fix and release notes
  CHANGELOG.md
  README.md
  glide.yaml
Labels: size/XS

#12 rename environment variables
  README.md
  main.tf
  venafi/resource_venafi_certificate_test.go
Labels: size/L

#13 add cloud url to pass tests
  main.tf
Labels: size/XS

#14 Linter
  .golangci.yml
Labels: size/XS
